Repository webrecorder/browsertrix, pull requests merged in 2024-03, with the labels that each got.

#1466 Browsertrix Cloud → Browsertrix frontend text rename
  .github/ISSUE_TEMPLATE/bug.yml
  README.md
  chart/email-templates/invite
  chart/email-templates/validate
  docs/deploy/ansible/digitalocean.md
  docs/deploy/ansible/k3s.md
  docs/deploy/ansible/microk8s.md
  docs/deploy/index.md
  docs/deploy/local.md
  docs/deploy/remote.md
  docs/develop/docs.md
  docs/develop/frontend-dev.md
  docs/develop/index.md
  docs/develop/local-dev-setup.md
  docs/index.md
  frontend/src/components/ui/README.md
  frontend/src/index.ejs
  frontend/src/index.ts
  frontend/src/pages/accept-invite.ts
  frontend/src/pages/join.ts
  frontend/src/pages/log-in.ts
  frontend/src/pages/org/settings.ts
Labels: front end

#1569 Frontend: Icon updates!
  frontend/src/assets/icons/copy-code.svg
  frontend/src/components/ui/copy-button.ts
  frontend/src/features/archived-items/crawl-status.ts
  frontend/src/pages/org/archived-item-detail.ts
  frontend/src/pages/org/archived-items.ts
  frontend/src/pages/org/browser-profiles-detail.ts
  frontend/src/pages/org/browser-profiles-list.ts
  frontend/src/pages/org/collection-detail.ts
  frontend/src/pages/org/collections-list.ts
  frontend/src/pages/org/workflow-detail.ts
  frontend/src/pages/org/workflows-list.ts
  frontend/tailwind.config.js
Labels: enhancement

#1609 Fix mismatch in prettier import order config
  frontend/prettier.config.js
Labels: tooling

#1615 Update node version mentioned in docs
  docs/develop/frontend-dev.md
  frontend/yarn-error.log
Labels: documentation

#1616 Clean up ESLint warnings in main
  frontend/src/components/ui/dialog.ts
  frontend/src/features/qa/page-qa-toolbar.ts
  frontend/src/pages/org/archived-item-qa.ts
Labels: front end

#1614 Emit more modern code for browsers
  frontend/package.json
Labels: tooling

#1546 QA page list sidebar
  .github/workflows/frontend-build-check.yaml
  .vscode/settings.json
  .vscode/snippets.code-snippets
  frontend/package.json
  frontend/src/components/ui/badge.ts
  frontend/src/components/utils/grouped-list.ts
  frontend/src/controllers/navigate.ts
  frontend/src/features/archived-items/item-list-controls.ts
  frontend/src/features/qa/index.ts
  frontend/src/features/qa/page-list/helpers/crawlCounts.ts
  frontend/src/features/qa/page-list/helpers/groupBy.ts
  frontend/src/features/qa/page-list/helpers/iconFor.ts
  frontend/src/features/qa/page-list/helpers/index.ts
  frontend/src/features/qa/page-list/helpers/issueCounts.ts
  frontend/src/features/qa/page-list/helpers/reviewStatus.ts
  frontend/src/features/qa/page-list/helpers/severity.ts
  frontend/src/features/qa/page-list/helpers/sortBy.ts
  frontend/src/features/qa/page-list/index.ts
  frontend/src/features/qa/page-list/page-list.ts
  frontend/src/features/qa/page-list/test-data.ts
  frontend/src/features/qa/page-list/ui/animate.ts
  frontend/src/features/qa/page-list/ui/index.ts
  frontend/src/features/qa/page-list/ui/page-details.ts
  frontend/src/features/qa/page-list/ui/page-group.ts
  frontend/src/features/qa/page-list/ui/page.ts
  frontend/src/features/qa/page-list/ui/render-item.ts
  frontend/src/features/qa/page-qa-toolbar.ts
  frontend/src/index.ts
  frontend/src/pages/org/archived-item-detail.ts
  frontend/src/pages/org/archived-item-qa.ts
  frontend/src/pages/org/index.ts
  frontend/src/shoelace.ts
  frontend/src/types/crawler.ts
  frontend/src/utils/weakCache.test.ts
  frontend/src/utils/weakCache.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: front end
