Repository webrecorder/browsertrix, pull requests merged in 2024-01, with the labels that each got.

#1455 Remove non-prod & optional dependencies when building frontend in ci
  .github/workflows/frontend-build-check.yaml
Labels: ops/deployment

#1459 Adds status information to user documentation
  docs/deploy/ansible/k3s.md
  docs/deploy/local.md
  docs/develop/docs.md
  docs/develop/local-dev-setup.md
  docs/overrides/.icons/bootstrap/check-circle.svg
  docs/overrides/.icons/bootstrap/dash-circle.svg
  docs/overrides/.icons/bootstrap/exclamation-triangle.svg
  docs/overrides/.icons/bootstrap/hourglass-split.svg
  docs/overrides/.icons/bootstrap/upload.svg
  docs/overrides/.icons/bootstrap/x-octagon.svg
  docs/overrides/.icons/btrix/status-dot.svg
  docs/stylesheets/extra.css
  docs/user-guide/archived-items.md
  docs/user-guide/browser-profiles.md
  docs/user-guide/crawl-workflows.md
  docs/user-guide/index.md
  docs/user-guide/org-settings.md
  mkdocs.yml
Labels: documentation

#1470 Hotfix: ignore everything in `./tests` and `playwright.config.ts` when checking types during webpack build
  frontend/webpack.config.js
Labels: bug

#1475 docs: Explains execution time
  docs/develop/docs.md
  docs/stylesheets/extra.css
  docs/user-guide/overview.md
  docs/user-guide/workflow-setup.md
  frontend/src/pages/org/dashboard.ts
  mkdocs.yml
Labels: documentation

#1512 Ensure linting & formatting runs in CI
  .github/workflows/frontend-build-check.yaml
  frontend/.eslintrc.js
  frontend/.prettierignore
  frontend/config/dev-server.js
  frontend/package.json
  frontend/src/components/ui/table/table-cell.ts
  frontend/src/features/archived-items/archived-item-list.ts
  frontend/src/features/archived-items/crawl-list.ts
  frontend/src/features/collections/collection-items-dialog.ts
  frontend/src/pages/crawls.ts
  frontend/src/pages/org/archived-items.ts
  frontend/src/pages/org/browser-profiles-list.ts
  frontend/src/pages/org/collection-detail.ts
  frontend/src/pages/org/collections-list.ts
  frontend/tailwind.config.js
  frontend/tests/README.md
  frontend/tests/login.spec.ts
  frontend/tsconfig.eslint.json
  frontend/webpack.config.js
Labels: enhancement, front end, ops/deployment
